config/routes.rb
Rails.application.routes.draw do
  root "pages#en"
  get "fr" => "pages#fr"
  get "services" => "pages#services"
  get "es" => "pages#es"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   def en
  end
  def fr
  end
  def es
  end
  def services
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">

    <div class="navbar-header">
      <%= link_to image_tag("mondialink.png", :alt => "Logo de Mondialink"), root_path %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <%= link_to image_tag("francais.png", :alt => "Icone Drapeau Français"), fr_path %><br><br>
        <%= link_to image_tag("espagnol.png", :alt => "Icone Drapeau Français"), es_path %><br>
      </ul>


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
</head>
<body>

	<%= render 'layouts/header' %>
  <div class="container">
  <% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>
	<%= yield %>
</div

</body>
</html>

app/views/pages/en.html.erb
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

<div class="container-fluid">
	<div class="jumbotron vertical-center">
	<p><h1 class="text-center">Cultural differences are a strong asset.</h1></p>
	<p><h2 class="text-center">Learn how to make the most of it !</h2></p>
</div>
</div>

<div class="container-fluid vertical-center">
<div class="btn-group btn-lg btn-justified">
	  <button type="button" class="btn btn-success"><h3>OUR SERVICES</h3></button>
	  <button type="button" class="btn btn-warning"><h3>OUR NETWORK</h3></button>
	  <button type="button" class="btn btn-info"><h3>OUR PARTNERS</h3></button>
</div>
</div>

app/views/pages/es.html.erb
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

<div class="container-fluid">
	<div class="jumbotron vertical-center">
	<p><h1 class="text-center">Las diferencias culturales son una riceza.</h1></p>
	<p><h2 class="text-center">Podrian ser una ventaja !</h2></p>
</div>
</div>

<div class="container-fluid vertical-center">
<div class="btn-group btn-lg btn-justified">
	  <button type="button" class="btn btn-success"><h3>NUESTROS SERVICIOS</h3></button>
	  <button type="button" class="btn btn-warning"><h3>NUESTRA RED</h3></button>
	  <button type="button" class="btn btn-info"><h3>NUESTROS SOCIOS</h3></button>
</div>
</div>

app/views/pages/fr.html.erb
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

<div class="container-fluid">
	<div class="jumbotron vertical-center">
	<p><h1 class="text-center">Les différences culturelles sont une richesse.</h1></p>
	<p><h2 class="text-center">Aimeriez-vous en tirer profit ?</h2></p>
</div>
</div>

<div class="container-fluid vertical-center">
<div class="btn-group btn-lg btn-justified">
	  <a href="services"><button type="button" class="btn btn-success"><h3>NOS SERVICES</h3></button></a>
	  <button type="button" class="btn btn-warning"><h3>NOTRE RESEAU</h3></button>
	  <button type="button" class="btn btn-info"><h3>NOS PARTENAIRES</h3></button>
</div>
</div>